exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock"]

safe: false
baselurl: /

destination: ./_site
lsi: false # not use related-posts
highlighter: pygments
markdown: redcarpet
permalink: /ja/entry/:year/:month/:day/:title

redcarpet:
  extensions:
    - autolink
    - tables
    - smart
    - disable_indented_code_blocks
sass:
  style: :compact
  compass: true

twitter_username: tasukuchan
production_url: https://blog.wktk.co.jp
default_image: /assets/images/wktk.png
site_name: グニャラくんの㍿ｗｋｔｋ運営日記
