# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

safe: false
lang: [en, ja]

destination: ./_site
lsi: false # not use related-posts
pygments: true
markdown: redcarpet
auto: false
permalink: /ja/:year/:month/:day/:title

title : Jekyll Bootstrap
tagline: Site Tagline
author :
  name : Tasuku SUENAGA a.k.a. gunyarakun
  email : blog@wktk.co.jp
  github : gunyarakun
  twitter : tasukuchan
  feedburner : feedname

production_url : http://blog.wktk.co.jp/

WktkBlog :
  version : 0.2.13

  BASE_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  comments :
    provider : disqus
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light

  analytics :
    provider : google
    google :
        tracking_id : 'UA-123-12'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  sharing :
    provider : false
