# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock"]

safe: false
baselurl: /
lang: [en, ja]

destination: ./_site
lsi: false # not use related-posts
pygments: true
markdown: redcarpet
permalink: /:categories/entry/:year/:month/:day/:title

default_update_policy:
  page:     "{% if page.raw.modified %}1{% endif %}"
  post:     "{% if page.raw.modified or page.previous.raw.yaml_modified or page.next.raw.yaml_modified %}1{% endif %}"

redcarpet:
  extensions: [autolink, tables, smart]

# TODO: ここから下見直す

production_url : http://blog.wktk.co.jp

WktkBlog :
  BASE_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
